import { Alg } from '../../types';

// TODO clear algs duplicates ?
// TODO make sure every algs are the same rotation
// Algs are coming from https://github.com/Roman-/zbll-trainer/blob/master/scripts/casesmap.js

const BBFF: Alg[] = [
  {
    family: 'BBFF',
    values: [
      "B2 D' R2 D' L' U L' U2 F2 L' D' L' D' R2",
      "R2 B2 R' B2 R' U R U' L U' L' U R'",
      "R2 D L D L F2 U2 L U' L D R2 D B2",
      "B U' F U F' U B' U' B L2 B L2 B2",
    ],
  },
  {
    family: 'BBFF',
    values: [
      "B2 D L2 D R U' R U2 F2 R D R D L2",
      "L2 D' R' D' R' F2 U2 R' U R' D' L2 D' B2",
      "B' U F' U' F U' B U B' R2 B' R2 B2",
      "L2 B2 L B2 L U' L' U R' U R U' L",
    ],
  },
  {
    family: 'BBFF',
    values: [
      "D F D2 B2 U' D2 F U' D B R2 B D2 F",
      "F U R' F2 L R D2 R' D' F' R D' F2 L'",
      "F U2 D' B2 D F2 U F U' D F D2 B2 D",
      "F U' R U2 L U2 L' U2 R' U F' L U' L'",
      "F D F2 D B2 U' D2 F U' D F D2 B2 D",
      "F D2 B2 U' D2 F U' D B R2 B D2 F D",
      "F B2 D2 B2 U' B U B2 D R2 D F' B",
      "F' U2 F2 B U2 B' U' B U2 F2 U F B'",
      "F' U2 F' U' L' U L F2 U' F' L F' L' F2",
      "B' R2 U' R D' R2 D R' U R2 B R' U R",
      "B' R2 F2 B R2 F' U' B U2 F2 U F B'",
      "B' R2 F' D2 B' D' B D2 F2 D R2 F' B",
    ],
  },
  {
    family: 'BBFF',
    values: [
      "D L2 U' F2 R U R' F2 L' U L2 D' L",
      "L' D L2 U' L F2 R U' R' F2 U L2 D'",
      "L2 U' F2 R U R' F2 L' U L2 D' L D",
      "L2 D F' D2 L2 U' B' U2 L2 B D L2 U' F'",
      "D' U' F' D F2 U' F R2 B U' B' R2 U F2",
      "L' U L2 F' L B D L' D' F L B' L2",
      "L' D F2 R' F R F D' L' F U F' L2",
      "L' B L B' L2 F' L' F L' U B' U' B",
      "L2 B L' F' D L D' B' L' F L2 U' L",
      "D U' F2 U' R2 B U B' R2 F' U F2 D' F",
      "L2 F U' F' L D F' R' F' R F2 D' L",
      "L' U L U' F R' F R F2 L F' L' F",
    ],
  },
  {
    family: 'BBFF',
    values: [
      "R2 U F2 L' U' L F2 R U' R2 D R' D'",
      "R2 B' R F D' R' D B R F' R2 U R'",
      "R2 F' U F R' D' F L F L' F2 D R'",
      "D' R2 U F2 L' U' L F2 R U' R2 D R'",
      "D R D' R2 U R' F2 L' U L F2 U' R2",
      "R D' R2 U R' F2 L' U L F2 U' R2 D",
      "D' U F2 U L2 B' U' B L2 F U' F2 D F'",
      "R U' R' U F' L F' L' F2 R' F R F'",
    ],
  },
  {
    family: 'BBFF',
    values: [
      "L2 B2 D2 R F2 L' U2 R U2 F2 L D2 R' B2 L2",
      "L2 B2 D2 L D2 L' F2 R F2 D2 R D2 R' B2 L2",
      "L2 B2 D2 R' B2 L U2 R' U2 B2 L' D2 R B2 L2",
      "L2 B2 D2 L' D2 L B2 R' B2 D2 R' D2 R B2 L2",
      "R2 B2 R' B2 U' L U' L' U R' U' R U R'",
      "L' U L U' L' U R' U' R U' B2 L' B2 L2",
      "L2 B2 L B2 U R' U R U' L U L' U' L",
      "R U' R' U R U' L U L' U B2 R B2 R2",
    ],
  },
  {
    family: 'BBFF',
    values: [
      "F' U' F L F2 D' F U F' D F2 U' L'",
      "F' U' L2 U' F2 U F2 U L2 F U' F U' F'",
      "F' U' L2 D' L2 U L2 D L2 F U' F U' F'",
      "F' D' B2 D' B2 D L2 D L2 F U' F U' F'",
      "B' R' F R B R' F2 L' F R F' L F",
      "L F L' B L F' L2 B' R B L B' R'",
      "L' B' R B' R D2 R' D2 B R' B2 L B'",
      "R' U' F2 D F' U F D' F2 R F U' F'",
      "R' U' R U' R B2 U R2 U R2 U' B2 U' R'",
      "R' U' R U' R B2 D B2 U B2 D' B2 U' R'",
      "R' U' R U' R B2 D B2 D L2 D' L2 D' R'",
      "R' F R2 B' R D2 B' D2 B R' B R' F'",
    ],
  },
  {
    family: 'BBFF',
    values: [
      "D' B2 D2 F' U D' F' U' F2 D' B2 U2 D F'",
      "F2 L F L' F U F2 L' U' L U F U2 F",
      "F' D2 B' R2 B' U D' F' U D2 B2 D2 F' D'",
      "B2 D2 F' U D' F' U D2 B2 D' F2 D' F' D'",
      "B2 D2 F' U D' F' U' F2 D' B2 U2 D F' D'",
      "L U L' F U' R U2 L U2 L' U2 R' U F'",
      "L F2 D R' F D R D2 L' R' F2 R U' F'",
      "L R' U' R2 U2 L' U L U2 L' R2 U2 R",
      "L R' U' R2 U2 L' U R B2 L' R2 B2 L",
      "L R' D' F2 D' R2 U' R' U R2 D2 L' R2",
      "L R' F2 D' L2 D2 R' D R D2 L F2 R",
      "R' U' R B' R2 U' R D' R2 D R' U R2 B",
    ],
  },
  {
    family: 'BBFF',
    values: [
      "F2 L2 D B' R2 B D' L2 F2 U' F U' F'",
      "D F2 L2 U R' F2 R U' L2 F2 D' L U' L'",
      "L2 U' L F' D2 B R' B' D2 F2 L' F' U L2",
      "L2 U' F L F2 D2 B R B' D2 F L' U L2",
      "L2 D' L B L2 D2 R F R' D2 L B' D L2",
      "L2 D' B L' D2 R F' R' D2 L2 B' L' D L2",
      "R2 U R' F D2 B' L B D2 F2 R F U' R2",
      "R2 U F' R' F2 D2 B' L' B D2 F' R U' R2",
      "R2 D R' B' R2 D2 L' F' L D2 R' B D' R2",
      "R2 D B' R D2 L' F L D2 R2 B R D' R2",
      "F2 R2 D' B L2 B' D R2 F2 U F' U F",
      "D' F2 R2 U' L F2 L' U R2 F2 D R' U R",
    ],
  },
  {
    family: 'BBFF',
    values: [
      "D B2 D2 F U' D F U' D2 B2 D F2 D F",
      "F D2 B L2 B U' D F U' D2 B2 D2 F D",
      "F2 R' F' R F' U' F2 R U R' U' F' U2 F'",
      "B2 D2 F U' D F U F2 D B2 U2 D' F D",
      "B2 D2 F U' D F U' D2 B2 D F2 D F D",
      "L U L' B L2 U L' D L2 D' L U' L2 B'",
      "L R' U L2 U2 R U' L' B2 L2 R B2 R'",
      "L R' U L2 U2 R U' R' U2 L2 R U2 L'",
      "L R' D F2 D L2 U L U' L2 D2 L2 R",
      "L R' F2 D R2 D2 L D' L' D2 R' F2 L'",
      "R' U' R F' U L' U2 R' U2 R U2 L U' F",
      "R' F2 D' L F' D' L' D2 L R F2 L' U F",
    ],
  },
  {
    family: 'BBFF',
    values: [
      "F U F' R' F2 D F' U' F D' F2 U R",
      "F U R2 U F2 U' F2 U' R2 F' U F' U F",
      "F U R2 D R2 U' R2 D' R2 F' U F' U F",
      "F D B2 D B2 D' R2 D' R2 F' U F' U F",
      "B L F' L' B' L F2 R F' L' F R' F'",
      "L U F2 D' F U' F' D F2 L' F' U F",
      "L U L' U L' B2 U' L2 U' L2 U B2 U L",
      "L U L' U L' B2 D' B2 U' B2 D B2 U L",
      "L U L' U L' B2 D' B2 D' R2 D R2 D L",
      "L F' L2 B L' D2 B D2 B' L B' L F",
      "R B L' B L' D2 L D2 B' L B2 R' B",
      "R' F' R B' R' F R2 B L' B' R' B L",
    ],
  },
  {
    family: 'BBFF',
    values: [
      "D' F' D' F2 D' B2 U D2 F' U D' F' D2 B2",
      "F U2 F U R U' R' F2 U F R' F R F2",
      "F U2 F2 B' U2 B U B' U2 F2 U' F' B",
      "F' U L' U2 R' U2 R U2 L U' F R' U R",
      "F' U2 D B2 D' F2 U' F' U D' F' D2 B2 D'",
      "F' U' L F2 L' R' D2 L D F L' D F2 R",
      "F' D2 B2 U D2 F' U D' B' L2 B' D2 F' D'",
      "F' D' F2 D' B2 U D2 F' U D' F' D2 B2 D'",
      "F' B2 D2 B2 U B' U' B2 D' L2 D' F B'",
      "B L2 U L' D L2 D' L U' L2 B' L U' L'",
      "B L2 F D2 B D B' D2 F2 D' L2 F B'",
      "B L2 F2 B' L2 F U B' U2 F2 U' F' B",
    ],
  },
];

const BFFB: Alg[] = [
  {
    family: 'BFFB',
    values: [
      "B2 F2 D' B2 L2 B' R2 F U2 B' D2 F' D B2 F2",
      "B2 F2 D' F2 R2 F' D2 B U2 F' R2 B' D B2 F2",
      "R2 L2 D R2 L2 U' R2 F2 R' B2 L D2 R' U2 L'",
      "R2 L2 D R2 L2 U' L2 B2 L' U2 R D2 L' B2 R'",
      "B2 F2 U' R2 B2 R' D2 L U2 R' B2 L' U B2 F2",
      "B2 F2 U' L2 F2 L' B2 R U2 L' D2 R' U B2 F2",
      "R2 U F R' B2 D' F2 L' F' D B2 F2 R'",
    ],
  },
  {
    family: 'BFFB',
    values: [
      "R2 U B U' F2 U B' D2 B2 D' B2 D' B2 D' L2 F2 D B2",
      "R2 U' R' D L2 D' R' D L2 R2 D' F2 U F2 R2",
      "R2 D' F' D B2 D' F' D F2 B2 U' F2 U F2 R2",
      "R2 U' R' D L2 D' R' D R2 L2 D' F2 U F2 R2",
      "L2 U' F2 R' D' L2 D R B2 U F2 U' B2 L2 F2",
      "L2 D' L2 F' D' B2 D F R2 D F2 U' B2 L2 F2",
      "F U F L2 B2 D2 F D' F' D' B2 L2 F2",
      "L' F' U L U L' U2 L U L' F L",
    ],
  },
  {
    family: 'BFFB',
    values: [
      "B' U D2 F U' F' D2 R2 D' F D R2 B",
      "L2 U F' B L2 F B2 U F2 U' B U F2 L2",
      "L U' B' R' D' F2 D R B U R U2 L' R'",
      "L' R D B D2 B2 D L B' R' U' B2 U2 B'",
      "R' U' R U L U2 R' U' L' U' L R U2 L'",
      "R' U' R U L U2 R' U' R U2 L' R' U R",
      "R' U' R F U' R' U' R U F' U R' U R",
      "R' D' F U B U2 F' U' F U2 F' B' D R",
      "R' D' F L U' F' U' F U L' U F' D R",
    ],
  },
  {
    family: 'BFFB',
    values: [
      "R D' R2 B2 D B2 U R B2 D' B2 U' R2 D",
      "D R D' R2 B2 D B2 U R B2 D' B2 U' R2",
      "F B U2 B R2 D F' L2 F D' R2 F' B2",
      "L U' L' U D F2 U R U2 R' F2 D' L",
      "R2 B2 R' U2 R' U' R2 B2 R2 U' R B2 R'",
    ],
  },
  {
    family: 'BFFB',
    values: [
      "R2 F2 R L F2 R F2 R2 L' F2 R' U2 R'",
      "L2 B2 R' F2 R' F2 R2 B2 L' U2 L2 U2 L",
      "F R D' R2 D' L2 D R2 D' L2 D2 R' F'",
      "F' L2 B D F D' B D F' D' B2 L2 F",
      "R F2 B2 L F2 L' B2 R' L2 D2 L' D2 L'",
      "B' D2 F R B R' F R B' R' F2 D2 B",
      "R' L' B2 U2 R B2 R' B2 U2 L' B2 R L2",
      "L' B2 L' D2 L' U2 L D2 L' U2 L2 B2 L",
      "B2 L2 B2 L U2 R' L2 U2 L F2 L2 F2 R",
      "R2 L' D2 R' B2 R' B2 R D2 R2 L U2 R",
      "R' L2 F2 R' D2 R' D2 R F2 R L2 U2 R",
      "B2 R L2 F2 R F2 R' D2 R' D2 L B2 L",
      "B R2 F2 R' B2 L2 B' R' B2 R' F2 R L2",
      "B' R2 F2 R' B2 L2 B R' B2 R' F2 R L2",
      "F' B' D2 B2 U' F2 U' B2 D R2 D F' B",
      "L2 F2 R' F2 R2 L2 U2 L' B2 L B2 U2 R'",
      "R2 F2 R2 U R B2 U' R F2 R' U B2 R'",
      "L2 B2 L2 U2 R2 L' B2 R U2 R' B2 R2 L",
      "L2 U2 F2 D2 F' U' F D2 F' U F' U2 L2",
      "R2 D2 U' F U' B2 U F' U' B2 D2 U2 R2",
      "L B2 D' B D' F2 D B' D' F2 D2 B2 L'",
      "L2 F2 L' F2 R D2 L' U2 L D2 U2 R' L'",
      "F2 B2 L2 F2 L' B2 L F2 L' B2 L' F2 B2",
      "R L D2 R L2 D2 R2 L' B2 R L2 B2 R'",
      "B R2 F2 R' B2 L2 B' R L2 F2 R' B2 R'",
      "B' R2 F2 R' B2 L2 B R L2 F2 R' B2 R'",
    ],
  },
  {
    family: 'BFFB',
    values: [
      "B2 D L' D' L2 U D L2 D' L U' L2 B2",
      "L2 U' F' L2 B' F U' F2 U' B U F2 L2",
      "B2 U L2 D' L' B2 L D L' B2 L' U' B2",
      "B2 U' R2 D L U2 L' D' R B2 R U B2",
      "B2 D' F2 D B U2 B' D' F R2 F D B2",
      "B' U2 F U F' U2 B2 U' F U B' U F'",
      "B' U2 B' D' F R2 F D B D' F2 D B",
      "L R F U2 R' U' R U' F' U' L' U R'",
    ],
  },
  {
    family: 'BFFB',
    values: [
      "B U' D2 F' U F D2 L2 D F' D' L2 B'",
      "R2 U' F B' R2 F' B2 U' F2 U B' U' F2 R2",
      "L U L' U' R' U2 L U L' U2 L R U' L'",
      "L U L' U' R' U2 L U R U L' R' U2 R",
      "L U L' F' U L U L' U' F U' L U' L'",
      "L D F' U' B' U2 F U F' U2 F B D' L'",
      "L D F' R' U F U F' U' R U' F D' L'",
      "L' R D' B' D2 B2 D' R' B L U B2 U2 B",
      "R' U B L D F2 D' L' B' U' L' U2 L R",
    ],
  },
  {
    family: 'BFFB',
    values: [
      "B2 D' R U' R2 U D R2 U' R' U R2 B2",
      "B2 D' R D R2 U' D' R2 D R' U R2 B2",
      "R2 U F R2 B F' U F2 U B' U' F2 R2",
      "B2 U L2 D' R' U2 R D L' B2 L' U' B2",
      "B2 D F2 D' B' U2 B D F' L2 F' D' B2",
      "B U2 F' U' F U2 B2 U F' U' B U' F",
      "B U2 B D F' L2 F' D' B' D F2 D' B'",
      "L' R' F' U2 L U L' U F U R U' L",
    ],
  },
  {
    family: 'BFFB',
    values: [
      "L' D L2 B2 D' B2 U' L' B2 D B2 U L2 D'",
      "D' L' D L2 B2 D' B2 U' L' B2 D B2 U L2",
      "F' B' U2 B' L2 D' F R2 F' D L2 F B2",
      "L2 B2 L U2 L U L2 B2 L2 U L' B2 L",
      "R' U R U' D' F2 U' L' U2 L F2 D R'",
    ],
  },
  {
    family: 'BFFB',
    values: [
      "F2 R2 D B2 R2 U R2 U' B2 R2 F' U F D' F' U' F'",
      "L2 U' F2 U F2 L2 D F U F D' F' U' F'",
      "D2 U2 R2 B2 R2 D2 U2 L' B2 L' F2 L B2 L",
      "B2 F2 R2 F2 R2 B2 F2 L' B2 L' F2 L B2 L",
      "R2 B2 L2 B2 R2 L2 F2 L' B2 L' F2 L B2 L",
      "R2 B2 L2 F2 R2 L2 B2 L' B2 L' F2 L B2 L",
      "L2 B2 R2 L2 B2 F2 R2 L' B2 L' F2 L B2 L",
      "B2 R2 L2 F2 L2 B2 R2 L' B2 L' F2 L B2 L",
      "F2 R2 L2 B2 L2 B2 R2 L' B2 L' F2 L B2 L",
      "F U' F2 U2 F' U' B' U F U' B U' F2 U F'",
      "B U B2 U R U R' U' B2 U R U' R' U2 B'",
      "R' U F' U' B U' F U B' U' F' U2 F U' R",
      "L' U B' U2 B' U F U' B U F' U B U' L",
      "R' U' F U R U' F' U' R U' B U2 B' U' R'",
      "F' U' L' U' B' U R' U2 R U B U L U' F",
      "R' U' F' U2 F U B U' F' U B' U F U R",
      "R' U2 R U B U2 B U L' U' B' U L U B'",
      "B2 L B' U' B U B L' B U B2 U2 B' U2 B'",
      "B U R' U2 L U R U' L' U R' U R U' B'",
      "R' U2 R U' B U' L' U' B U L U' B' U2 B'",
      "R U' B2 U B' U' B' U R B R' B2 R B R2",
      "R B R U R' B2 R U' R' U B2 U' B' R'",
      "R' U2 R U' F' B L2 F L' U' L2 U L B'",
      "R' U2 R U' F B' R2 B R U R2 U' R' F'",
      "R' U2 R2 U R F' R U R U' R' F R2 U' R'",
    ],
  },
  {
    family: 'BFFB',
    values: [
      "L' D F2 U F2 L2 U' L' U D2 R2 D' R2 D' L2 D'",
      "L' D F2 U F2 L2 U' L' U2 D F2 D' F2 U' L2 D'",
      "L' D F2 U F2 L2 U' L' U' L2 D' L2 U2 D L2 D'",
      "L' D F2 U F2 L2 U' L' D' B2 D' B2 U D2 L2 D'",
      "R2 U F2 L D R2 D' L' B2 U' F2 U B2 R2 F2",
      "R2 D R2 F D B2 D' F' L2 D' F2 U B2 R2 F2",
      "F' U' F U2 B2 L2 F D F D' F2 L2 B2",
      "F' U' F' R2 B2 D2 F' D F D B2 R2 F2",
      "R F U' R' U' R U2 R' U' R F' R'",
    ],
  },
  {
    family: 'BFFB',
    values: [
      "B L2 F B' U' F' U2 B2 R2 F' D' F R2 B2",
      "B' R2 F' B U F U2 B2 L2 F D F' L2 B2",
      "B' R2 B F' U F U2 B2 L2 F D F' L2 B2",
      "F L F' R' F R F R' F R F' L' F'",
      "F R U' R' U R U R' U R U' R' F'",
      "F' L' U L U' L' U' L U' L' U L F",
      "F' R' F L F' L' F' L F' L' F R F",
      "L U2 L D' B2 L' B2 L U B2 U D L'",
      "L' B2 R' F D2 R D2 R' B' D2 F' B' L",
      "R B2 L F' D2 L' D2 L B D2 F B R'",
      "R' U2 R' D B2 R B2 R' U' B2 U' D' R",
    ],
  },
];

const FFLR: Alg[] = [
  {
    family: 'FFLR',
    values: [
      "F' B U L2 U2 F U F D F D' F2 B'",
      "F' B2 D' B D B U B U2 L2 U F B'",
      "B L D' L' D F2 B' L U F2 L' U' F2 L'",
      "B' D' R U' R U R U' R2 D R' U R B",
      "B' R U' R U D' R U' R' D R2 U R B",
      "B' R U' R2 F' R' U R U' F R U R B",
      "B' R2 U' B' R2 U B L' R2 D B' D' B L",
      "L F U F R U' F U F' R' F2 U' F L'",
      "L F U F2 D F' U' F U D' F U' F L'",
      "L F U F' D F2 U' F U F U' F D' L'",
    ],
  },
  {
    family: 'FFLR',
    values: [
      "R2 U' F2 L' U R2 U' L U2 F2 D R2 U2 D' F2",
      "L2 U' F' D' F U' F' D F L2 U L2 U L2",
      "L2 D' L' D' L U' L' D L B2 U B2 D L2",
      "L2 B D' B' U' B D B' U' L2 U L2 U L2",
      "L2 B D' B' U' B D B' D' B2 U B2 D L2",
      "D' L2 U' F' D' F U' F' D F L2 D F2 U F2",
      "D' L2 B D' B' U' B D B' U' L2 D F2 U F2",
      "F L F' D' L U' L B' L' B' U B2 D L2",
      "B2 R' U R U' B2 D L U2 L' D F2 U F2 D2",
      "B2 R' U R D' R2 U R U2 R' U R2 D B2",
      "L U2 L' U F2 L U L2 D' L' D L2 U' F2",
    ],
  },
  {
    family: 'FFLR',
    values: [
      "B2 F D B' D' B' U' B' U2 R2 U' B F'",
      "B' F U' R2 U2 F' U' F' D' F' D B F2",
      "F B2 D B' D' B' U' B' U2 R2 U' F' B",
      "F B' U' R2 U2 F' U' F' D' F' D F2 B",
      "B D L' U L' U' L' U L2 D' L U' L' B'",
      "B L2 U B L2 U' B' L2 R D' B D B' R'",
      "B L' U L2 F L U' L' U F' L' U' L' B'",
      "B L' U L' U' D L' U L D' L2 U' L' B'",
      "B' R' D R D' F2 B R' U' F2 R U F2 R",
      "R' F' U' F D' F2 U F' U' F' U F' D R",
      "R' F' U' F2 D' F U F' U' D F' U F' R",
      "R' F' U' F' L' U F' U' F L F2 U F' R",
    ],
  },
  {
    family: 'FFLR',
    values: [
      "F' D2 B2 D' B R2 F L2 B U' F2 D F2 L2 D L2",
      "B L2 U' R2 D2 R2 U' R2 F L2 D2 R2",
      "L B L U L2 U' L' B' L U2 L2 U2 L2",
      "L2 U B' R B L2 B' R' B U L2 U2 L2",
      "B U B2 R D' R D R2 B R U B U' B' R'",
      "L U2 R' U R F R U' R' U2 F' R' L' U2 R",
      "B U' F R' F' R U F' B' U2 L' U2 L U F",
      "B L U L' U' B2 R' U' L U' R U L' U B",
      "B L U L' U' B2 R' U2 R U F' U B U' F",
      "L D' L' U L U B' L' U2 L U2 B D U' L'",
      "F' L' U' R U B2 R B2 R' U' R' U L U F",
      "L' B2 U' R' U R B2 R' L U L' U' R U L",
      "B L U L' U' L' B' R' L U2 R B2 L' B2 L",
      "L U2 R' U R U2 R' L' F' U2 L' U' L F R",
      "L U2 R' U R U2 L' U' R2 L F2 R F2 R L'",
      "F' D B U' F' U F B' U F' U2 F D' U2 F",
      "B' L' B U2 F U' B' U F' B U B' U2 L B",
      "F' B L' U B' U' L F L' B L B' R' U2 R",
      "L U B' R B L' B' U R2 U' R' F R2 F' B",
      "L F U' B U2 F' B' L2 B2 L B U B2 U' B'",
      "B L2 U L U' B' U2 L' U2 L B U L U' B'",
      "B U B L2 B' U' L2 U L2 U' B' U2 F U2 F'",
      "B2 L B U B' L' B U' B L' B2 R B2 R' L",
    ],
  },
  {
    family: 'FFLR',
    values: [
      "F2 R2 F2 U2 F2 R2 F' R2 U' R2 U2 R2 U R2 F'",
      "F2 L2 B2 D2 B2 L2 F' R2 D' F2 U2 F2 D R2 F'",
      "F2 R2 F2 U2 F2 R2 F' R2 D' F2 U2 F2 D R2 F'",
      "F2 D2 B2 D2 F' R2 U R2 D U2 B2 D' U F'",
      "F2 D2 B2 D2 F' D U' B2 D' U2 R2 U' R2 F'",
      "L2 B2 U' L2 F' L2 U B2 D2 B D2 U' L2 F",
      "B' R2 D' F2 D' F2 D2 R2 B2 U2 B'",
      "B' U2 B2 L2 D2 F2 D' F2 D' L2 B'",
    ],
  },
  {
    family: 'FFLR',
    values: [
      "F U R' F R F2 L R' D F' D' L' R",
      "F U R' F' L R' D2 R D' F' D' L' R",
      "F U2 F' B' U F U' F' B U' F U' F'",
      "F' L B L2 U L2 U' L' B' U L' U' F",
      "B U B' U F' B U F U2 F' B' U F",
      "B U B' U F' B U B' U' F B U2 B'",
      "B U B' U' F B' R B2 U' B' U R' F'",
      "B U B' U' F B' R2 D B' D' B2 R2 F'",
      "B U2 D2 R2 U' F' U2 R2 D2 B' U L2 B'",
      "B U2 D2 R2 U' B' R2 D2 L2 F' U L2 B'",
      "B L2 U' F L2 D2 R2 B U R2 U2 D2 B'",
      "B L2 U' B D2 R2 U2 F U R2 U2 D2 B'",
    ],
  },
  {
    family: 'FFLR',
    values: [
      "B U2 B2 R2 U L2 D' F2 R2 D L2 U B'",
      "B U2 B2 R2 D F2 D' R2 B2 U L2 U B'",
      "B U' L2 U' B2 R2 D F2 D' R2 B2 U2 B'",
      "B U' L2 D' R2 F2 D L2 U' R2 B2 U2 B'",
      "B D2 F2 L2 D B2 U' F2 R2 U B2 D B'",
      "B D' B2 U' R2 F2 U B2 D' L2 F2 D2 B'",
      "B' U R2 U B2 L2 D' F2 D L2 B2 U2 B",
      "B' U R2 D L2 F2 D' R2 U L2 B2 U2 B",
      "B' U2 B2 L2 U' R2 D F2 L2 D' R2 U' B",
      "B' U2 B2 L2 D' F2 D L2 B2 U' R2 U' B",
      "B' D B2 U L2 F2 U' B2 D R2 F2 D2 B",
      "B' D2 F2 R2 D' B2 U F2 L2 U' B2 D' B",
    ],
  },
  {
    family: 'FFLR',
    values: [
      "R2 B2 U R2 F R2 U' B2 D2 B' D2 U R2 F'",
      "F2 D2 B2 D2 F L2 U' L2 D' U2 B2 D U' F",
      "F2 D2 B2 D2 F D' U B2 D U2 L2 U L2 F",
      "F2 D' L2 F L2 D F2 R2 D2 B' D2 U R2 F'",
      'B L2 D F2 D F2 D2 L2 B2 U2 B',
      'B U2 B2 R2 D2 F2 D F2 D R2 B',
    ],
  },
  {
    family: 'FFLR',
    values: [
      "R' U2 R B' U B' L' R2 F D' F' L R2 B2",
      "R' U L U' R B2 D2 R F2 D R' D B2",
      "F R' B' R2 U' R2 U R B U' R U F'",
      "F' U2 F B U' F' U F B' U F' U F",
      "F' U' L F L R' D2 L' D F D L' R",
      "F' U' L F' L' F2 L R' D' F D L' R",
      "B U F' B' U2 B U F B' U F' U F",
      "B U' B' U2 L' U2 L U B L' U L B'",
      "B' U2 D2 L2 U F U2 L2 D2 B U' R2 B",
      "B' U2 D2 L2 U B L2 D2 R2 F U' R2 B",
      "B' R2 U F' R2 D2 L2 B' U' L2 U2 D2 B",
      "B' R2 U B' D2 L2 U2 F' U' L2 U2 D2 B",
    ],
  },
  {
    family: 'FFLR',
    values: [
      "R2 D F D2 F2 U' F U F D2 F' D' R2",
      "L2 B' L2 F L2 D F' D' L2 U B U F'",
      "B' R2 U' R2 B' D' F' R2 F D B U B",
      "R2 U L D2 L2 U' L U L D2 L' U' R2",
      "L' D' R2 D2 L U L U' L2 D2 R2 D L",
      "F R B2 D2 F L D F' D B R F' B",
      "B' R2 U' R2 U R2 U2 L2 D2 F' R2 D2 L2",
      "B' R2 U' R2 U R2 D2 L2 U2 F' L2 D2 R2",
      "B' R2 D F2 D2 F2 D' U2 L2 F' R2 D2 L2",
      "B' R2 D' U2 B2 D2 B2 D L2 F' R2 D2 L2",
      "B' U2 L2 D2 L2 U R2 U' L2 F' R2 D2 L2",
      "F R U' R' U' R U2 R2 U' R F' R' U R",
      "R' U L' U' R U L F U' F' U' F U2 F'",
      "B U' B' U' L U' L' U B U2 B' L U2 L'",
      "B R' U F U' F' U' R U B' U' F U2 F'",
      "B' R' U F U' F' U' R U B U' F U2 F'",
      "F U' L' U R U' R' L U' R U2 R' U' F'",
      "R' U' L U2 L' U2 R U2 R' U' R L U2 L'",
    ],
  },
  {
    family: 'FFLR',
    values: [
      "L F L' R B L R' F' L' R B' R'",
      "L F L' R B2 L F' L' F B2 R' F'",
      "L F L' R' B2 L F' L' F B2 R F'",
      "L' B D F' L' F D' B' L U F U F'",
      "R' U B L B' U' R U R B L' B' R'",
      "R' U L U' F' R B' R' F R B U L'",
      "R' U R U B L' D' R B' R' D L B'",
      "R' F' U' F R B L F U F' L' B'",
      "R' F' L R B2 R' F R F' B2 L' F",
      "R' F' L' R B2 R' F R F' B2 L F",
      "R' F' L' R B' L R' F L' R B L",
      "R' F' L' R B' R' U B L F B' R B",
    ],
  },
  {
    family: 'FFLR',
    values: [
      "R2 U F D F' U F D' F' R2 D' F2 U' F2 D",
      "R2 U2 F' L' F R F' L F R U' R2 U' R2",
      "R2 U2 F' L' F R F' L F R D' F2 U' F2 D",
      "R2 U2 R B L' B' R B L B' U' R2 U' R2",
      "R2 U2 R B L' B' R B L B' D' F2 U' F2 D",
      "R2 D R D R' U R D' R' B2 U' B2 D' R2",
      "R2 B' D B U B' D' B U R2 U' R2 U' R2",
      "R2 B' D B U B' D' B U R2 D' F2 U' F2 D",
      "R2 B' D B U B' D' B D B2 U' B2 D' R2",
      "R' U2 R U B2 L U' L2 D L' D' L2 U B2",
      "R' U2 R U' F2 R' U' R2 D R D' R2 U F2",
    ],
  },
];

const FRLF: Alg[] = [
  {
    family: 'FRLF',
    values: [
      "F' L U2 L D R' F2 R D R2 B' R2 D2 L2",
      "B2 R2 B U' B' L2 R2 U' F D F' U L2 B2",
      "L2 U2 B D' B' U B D F' L2 F B' U' L2",
      "L2 U' F' B L2 B' D' F U F' D F U2 L2",
      "F' B2 D' B2 U B' U' B2 D2 L2 D' F B'",
      "F' B2 D' B2 U B' D B2 U2 L2 U F B'",
      "F' R D2 R' U2 R D2 R' F U F' U F",
      "B U L' B' R' B L B' R U B U2 B'",
      "B D L2 F' L2 F U' D F U F' D2 B'",
      "R U' R' F R2 U F' R F U' R F' R",
    ],
  },
  {
    family: 'FRLF',
    values: [
      "B' R2 F R2 B' R2 F D' F' D F' R2 B2",
      "L2 D R L2 U2 L U' R' F2 U' L2 D' L",
      "F' U2 F2 D F D2 B L2 B D' B2 D2 F2",
      "R2 D R2 U R U2 R D L' B2 L D2 R2",
      "R' F' R U' F U' R2 D2 L' B L D2 R2",
      "D' F D2 B2 D B' L2 B' D2 F' R2 U R2",
      "L2 B2 R' L2 U L F2 D R2 D R' L' F2",
      "F R2 B2 D2 F D F' D' B D2 F' R2 B",
      "B2 D' B2 U2 B D2 F' L2 F D2 B D B2",
      "B' R2 F2 D2 B' D F' D' B D2 F' R2 B",
      "F D2 B2 D B' L2 B' D2 F' R2 U R2 D'",
      "B2 U' L2 U2 L D2 R' F2 R D2 L U B2",
      "R' U' L' U' L U2 R' U L' U' R U' R L",
      "R' U L' U L U' R U2 L' U R' U R L",
      "R' U R U2 L' U' L U2 R' U L' U2 R L",
      "R B U' B' U F U F' R' F U' F2 U2 F",
      "R' U L' U2 R L U2 R' U' R U2 L' U L",
      "R' U R U2 R' L' U2 L U' R U2 L' U L",
      "R' F R U R' F U' F2 U F L F R L'",
      "R' U L F L' F U F2 U' F' L F' R L'",
      "R' U L' U' R U' L U2 R' U L' U' R L",
      "R B L B' R' B L' B2 U' B U' B' U2 B",
      "B' U' B L U' B U B' L' B U' B2 U2 B",
      "F' U2 F U2 B' U2 B U' F' U B' U2 F B",
      "B U2 F' B' U2 F U F' U' B U2 B' U2 F",
    ],
  },
  {
    family: 'FRLF',
    values: [
      "D' F2 D R2 U' B2 R' D L2 D' R B2 R2",
      "F2 D R2 U' B2 R' D L2 D' R B2 R2 U2 D'",
      "L B2 D' R U' R U R' D B2 L U' L2",
      "L2 D2 R2 D R B2 R' D L' D2 R2 D2 L'",
      "R2 D L R' B2 L D2 L2 R D R U2 R",
      "R2 D' L2 R' D2 L' B2 L' R D' R U2 R",
      "R2 D' L' U2 L2 F2 L2 U2 L D R U2 R",
      "R2 D' L' D2 R2 B2 R2 D2 L D R U2 R",
      "R2 D' L' R' U2 R' B2 L' U' L B2 L F2",
      "R2 D' R' F2 R2 U2 R2 F2 R D R U2 R",
      "R2 D' R' B2 L2 D2 L2 B2 R D R U2 R",
      "R' U2 F U F' R F U2 R' U' R U F'",
    ],
  },
  {
    family: 'FRLF',
    values: [
      "D L2 F2 B2 U F U' B2 U F D' L2 U B2 U' B2",
      "F U F D' L2 B2 D2 F D' F' D' B2 L2 D F2",
      "B2 L2 F B U' B U R2 F D2 B' D2 R2 F2 L2",
      "L' U' L' F2 R B2 R D R' B2 R' F2 L2",
      "L U' L U L' D F2 U2 F2 L' U' L U D'",
      "L U' L U L' D F2 U2 F2 L' U' L D'",
      "D' L U' L U L' D F2 U2 F2 L' U' L",
      "L U L' U L U2 L2 U R U' L U R'",
    ],
  },
  {
    family: 'FRLF',
    values: [
      "R2 D L U' R2 U L' U2 R2 U R2 D' R2 U R2",
      "R2 D L U' R2 U L' D2 L2 U L2 D' L2 U L2 D2",
      "R2 U B U' F2 U B' U2 F2 U F2 D' F2 D R2",
      "R2 U B U' F2 U B' U2 F2 D R2 D' R2 U R2",
      "D2 R2 D L U' R2 U L' D2 L2 U L2 D' L2 U L2",
      "F2 R2 D B2 R D' L2 D R' D' R2 U F2 U' L2 F2",
      "F' U2 F2 D F D2 F U2 F U' B2 U F2 B2 D F2",
      "L U2 L2 B2 D2 R' D2 B2 L U' B2 D' R2 D B2",
      "L U2 L' U' L' D L2 U' L' U L2 D' L2",
      "R2 U' F R2 F' D B U2 B' U D' R2",
      "R' L F R U' R' U L U L' F' L U' L2 U' R",
      "L U L' U' L' U' B U L2 U2 L' U B' R' U R",
      "R' U L F2 U' F' U' F' U2 F U' F U L' U R",
      "R' U' F U F' R U F' U2 F2 U F2 U F2 U' F'",
      "L U2 L' U B' U' B' U' B U2 B' R' U R U' B2",
      "B' R' B R U2 R2 U' B U' B' U R' B' R' B R'",
      "L U2 L' U' L' U B' U' B2 D L' D' B' L2",
      "R' U2 R U' L' U R B2 R' L' B2 L U' L",
      "R' U2 R U' L' U L' B2 R L B2 R' U' L",
      "L U' R' U L' U2 R U' L U' R' U L' U2 R",
      "L U2 L' U' L U B D' B' U' B D B' U' L'",
      "L U2 F' U R' U F U F' U' R U2 F U2 L'",
      "R' U2 R U' F2 U' F R' F U' F' R F' U F2",
      "R' L F U F2 U' F2 U' F' R U' L' B' U B",
      "L F B2 R B' U' B R' B' U B' U F' U' L'",
      "R' L F U F2 U' F L' F' U' F U F R' F' R2",
      "B R B' U B R' U B' U R U R' U' B U2 B'",
      "R U R2 U R' F R F' U' R2 U' R' U2 B U' B'",
      "L U' R U R2 F R F U F2 U' F' R' F' R L'",
      "L U' B' U' B U B' U' B L U2 L' U2 B L' B'",
    ],
  },
  {
    family: 'FRLF',
    values: [
      "F2 U F2 U' F2 L2 F2 R U' L2 U R' F2 L2",
      "D F2 U F2 D' L2 B2 L2 F U' B2 U F' L2 B2",
      "D R F2 U2 R U2 F2 D' R2 U2 R' U F2 U R2",
      "F U B' R2 B U' B2 L2 F D' F' L2 F' B2",
      "F R B L' U L B' L' U2 L U R' F U F2",
      "F2 U F2 D' L2 B2 L2 F U' B2 U F' L2 B2 D",
      "B U2 R U R' B' U R U2 R' B U2 B'",
      "B L B' U2 B L' B2 D2 F R' F' D2 B",
      "B' L' B D2 L D2 R' D2 F2 L' F R F D2",
      "L' B2 L' F2 R F R2 F L B' D2 B' L",
      "R' U2 L' D2 R D R2 D L U' B2 U' R",
    ],
  },
  {
    family: 'FRLF',
    values: [
      "F2 L2 F2 U' F2 L2 D' B L2 B' D B L2 B' F2",
      "B' U F R2 D' F D F2 U2 B U2 B2 R2 B2",
      "D2 B' U F R2 D' F D F2 U2 B D2 F2 L2 F2",
      "D2 B' U F R2 D' F D B2 D2 B U2 B2 L2 F2",
      "B' U F R2 D' F D B2 D2 B D2 F2 R2 B2",
      "F2 R2 L2 U' L' U B2 D B2 L2 D' L' D R2 F2",
      "B' U2 L U2 B U2 F2 U' B' U F2 L' U' B",
      "B' U F R2 D' F' U2 F' U2 F2 D R2 F' B",
      "B' U F2 L2 F' R' F L2 F' R U' B U F'",
      "B' R2 D2 L F L2 F L2 F2 L' D2 R' B R'",
      "F' L F R2 F D' F2 D L' D' F2 D F' R2",
      "B' U' B2 L' B' L2 F' U2 F2 U F2 U F L'",
    ],
  },
  {
    family: 'FRLF',
    values: [
      "R2 B2 F2 U' R F2 R' U L D2 L' B2 F2 R2",
      "B2 L2 F D' F' R2 L2 D' B U B' D R2 B2",
      "L2 F2 U' L2 U R' L2 D' L2 D R L2 F2 L2",
      "F R2 D L' U B U' B' U' L D' U R2 F'",
      "F R2 L' D U B U' B' D' U' L U R2 F'",
      "F R2 D U L B L' U' L B' L' D' R2 F'",
      "R U R2 F2 L D' R' L2 D' R D R L F2",
      "R' U' F' U' B' U2 F U B U' R L U2 L'",
    ],
  },
  {
    family: 'FRLF',
    values: [
      "D B2 R2 D' B' D F2 D' F2 B D' F2 U F2 R2 U' B2",
      "F' D' F2 U F2 U F' U' D F' R2 U2 R2 U F2",
      "L2 B D' B U' D B D' B D B' U B2 L2",
      "R2 F U' F U D' F U' F U F' D F2 R2",
      "B' R' U2 B U2 B2 U2 L' B' L U2 R B2",
      "F U' B D' L2 D B' U2 F U F2 U2 F'",
      "B L' B R' D2 R B' L2 F L F2 L2 B'",
    ],
  },
  {
    family: 'FRLF',
    values: [
      "F U F' U2 L2 B' U' B U' L2 U L2 U L2",
      "F U F' U2 L2 F U2 F' U2 F' L2 F2 U F'",
      "R' L' U2 L U L F2 U F2 U' R' L' F2 R2",
      "F U F' U2 L2 B L2 F' L2 B' L2 F2 U F'",
      "F U F' U2 R2 F' D' F D' L2 D L2 D R2",
      "F U F' U2 R2 F' D' F U' F2 D F2 U R2",
      "F U F' U2 L2 B' U' B D' B2 U B2 D L2",
      "F2 U L2 F2 U R U' L2 U L U2 R' L' F2",
      "L2 D' B D L U2 B' U2 L' B2 L U B L",
      "F U F' U B' U B L2 B L2 B' U B' U2 B",
      "L F R' F R F2 U F' U2 F2 U F2 U F L'",
      "F U F' U B' U F U2 B U2 F' U B' U2 B",
      "F' R' F' R U' F U F2 U' F' R U R' U F2",
      "L F U F2 L F L' F' U2 F2 U F2 U F L'",
      "B U' F U F' B' R' U2 R U F R' U R F'",
      "F U F' U F' L F L2 B L2 F' L B' L2 F",
      "F U F' U2 L2 B L2 B' U2 B' U2 F B U F'",
      "B2 U' B2 U' B D' U2 B U' B' D U' B U B2",
      "B U B' U B' U' B' U2 F D' R2 D F' U B'",
      "B L F' B' U F U L' F' R' F' R U2 F L",
      "L' B D' U' F R' F' D U B U B L' B L2",
      "R' L' U2 L U' R U2 F B R U R' F' U B'",
    ],
  },
  {
    family: 'FRLF',
    values: [
      "R2 D L U' R2 U L U' R2 U L2 D' R2",
      "F D2 F2 U' F U2 F D2 F' B2 U B2",
      "F D2 B2 D' F D2 F U2 F' B2 D F2",
      "F2 L2 B D' B' U' B D B' U L2 F2",
      "F2 R2 F U' F' D' F U F' D R2 F2",
      "B2 L2 F D' F' U' F D F' U L2 B2",
      "B2 R2 B U' B' D' B U B' D R2 B2",
      "L2 U F' D' F U F' D F U2 L2",
      "L2 U2 B D' B' U B D B' U L2",
      "R2 D B' U' B D B' U B D2 R2",
      "R2 D2 F U' F' D F U F' D R2",
      "B D' F' U' F' U B2 U' F U F B2 D B'",
      "R' L' U2 L U' R U L U' R' U L2 U2 R L",
      "B U' R L' U R' U' L2 U R U' R' L' U B'",
      "F' R' F R U' L' U R U' L U R2 F' R F",
      "F' U' L' U F' B' U' F U B U' L F' U F2",
      "B D' F B' U F' U' B2 U F U' F' B' D B'",
      "R U' R' L' U2 L U L2 U R U' L U L U2 R'",
      "R2 D2 U' L' U' L D L' U L D U R2",
      "R2 U2 R F' U' B' U F U' B U R' U2 R2",
      "L2 U2 L' B' U' F' U B U' F U L U2 L2",
      "R2 U2 R U2 L U' R U L' U' R' U' R' U2 R2",
      "L2 U2 L' U2 R U' L U R' U' L' U' L U2 L2",
      "R L B U B' U F U' B U F' U2 B' R' L'",
      "F R' F R' U R D R' D' U' R F' R U F'",
      "L F' L' U B' U F U' B U F' U2 L F L'",
      "F U F' U2 B' U2 B U2 B L2 B' L2 F U F'",
      "B U' B L' B' L U2 F U' B' U F' R' U' R",
      "B U' B U R D R' U R D' R' U2 B' U B'",
    ],
  },
  {
    family: 'FRLF',
    values: [
      "B2 D' F2 D2 B U2 B' D2 F R2 F D B2",
      "F2 U2 F2 B' D B R2 U R2 U2 B' D' B",
      "B2 U' R2 D2 L U2 L' D2 R B2 R U B2",
      "F D2 B2 D' F D2 B L2 B D F2",
    ],
  },
];

const LFFR: Alg[] = [
  {
    family: 'LFFR',
    values: [
      "D' B2 L2 D B D' F2 D F2 B' D F2 U' F2 L2 U B2",
      "F D F2 U' F2 U' F U D' F L2 U2 L2 U' F2",
      "L2 F' U F' U' D F' U F' U' F D' F2 L2",
      "R2 B' D B' U D' B' D B' D' B U' B2 R2",
      "B L U2 B' U2 B2 U2 R B R' U2 L' B2",
      "F' U B' D R2 D' B U2 F' U' F2 U2 F",
      "B' R B' L D2 L' B R2 F' R' F2 R2 B",
    ],
  },
  {
    family: 'LFFR',
    values: [
      "L2 U' B' U F2 U' B U2 F2 U' F2 D F2 D' L2",
      "L2 U' B' U F2 U' B U2 F2 D' L2 D L2 U' L2",
      "L2 D' R' U L2 U' R U2 L2 U' L2 D L2 U' L2",
      "L2 D' R' U L2 U' R D2 R2 U' R2 D R2 U' R2 D2",
      "D2 L2 D' R' U L2 U' R D2 R2 U' R2 D R2 U' R2",
      "F U2 F2 D' F' D2 F' U2 F' U B2 U' F2 B2 D' F2",
      "F2 L2 D' B2 L' D R2 D' L D L2 U' F2 U R2 F2",
      "L2 U F' L2 F D' B' U2 B U' D L2",
      "L' U' L U R' U R U2 L' U L U' R' U R",
      "R' U2 R U R' U L U L' U' R U L U' L'",
      "B U2 B' U' B U' B' U' B U' F' U B' U' F",
      "L U F' U' F U L' U L U2 L' U F' U2 F",
      "R' U R U2 R' U' R U F' U2 R' U' R U' F",
      "L' U' B U B' L B U' B2 U2 B U B' U B",
      "R' U' R' U L U' R U L' U2 R U R' U R",
      "R' U R U' F U' R' U' R U F' U2 R' U' R",
      "R' U R U' F' U R' U R U2 F U' R' U R",
      "R' U2 R U F U F U' R' U R U F' U2 F'",
    ],
  },
  {
    family: 'LFFR',
    values: [
      "F' U' F U2 R2 B U B' U R2 U' R2 U' R2",
      "F' U' F U2 R2 F' U2 F U2 F R2 F2 U' F",
      "R L U2 R' U' R' F2 U' F2 U R L F2 L2",
      "F' U' F U2 R2 B' R2 F R2 B R2 F2 U' F",
      "F' U' F U2 L2 F D F' D R2 D' R2 D' L2",
      "F' U' F U2 R2 B U B' D B2 U' B2 D' R2",
      "F' U' F U2 L2 F D F' U F2 D' F2 U' L2",
      "F2 U' R2 F2 U' L' U R2 U' R' U2 R L F2",
      "R2 D B' D' R' U2 B U2 R B2 R' U' B' R'",
      "F' U' F U' B U' B' R2 B' R2 B U' B U2 B'",
      "R' F' L F' L' F2 U' F U2 F2 U' F2 U' F' R",
      "F' U' F U' B U' F' U2 B' U2 F U' B U2 B'",
      "F L F L' U F' U' F2 U F L' U' L U' F2",
      "R' F' U' F2 R' F' R F U2 F2 U' F2 U' F' R",
      "B' U F' U' F B L U2 L' U' F' L U' L' F",
      "F' U' F U' F R' F' R2 B' R2 F R' B R2 F'",
      "F' U' F U2 R2 B' R2 B U2 B U2 F' B' U' F",
      "B2 U B2 U B' D U2 B' U B D' U B' U' B2",
      "B' U' B U' B U B U2 F' D L2 D' F U' B",
      "B' R' F B U' F' U' R F L F L' U2 F' R'",
      "R B' D U F' L F D' U' B' U' B' R B' R2",
      "R L U2 R' U L' U2 F' B' L' U' L F U' B",
      "B2 D L' U L U' L2 U L' D' U' B2 R' U' R",
      "F' U' F U2 R2 B' R2 B U2 F' U F B U2 B'",
      "F' U' F U' F R' B' D2 B' D2 B R' B R2 F'",
      "R L U2 R' U' R' F2 U' F2 U F2 R2 U2 R' L'",
      "F L F L' U L F2 L' U2 R' F' D' F' D R",
      "F' L' B' U2 R' U2 L' U R U' L2 F L' B L",
    ],
  },
  {
    family: 'LFFR',
    values: [
      "R' B2 R U' R2 U2 R2 U' R2 U' R B2 R",
      "B U L2 U2 L2 B2 D' B D' R2 D R2 D",
      "F2 U2 F2 B D' B' L2 U' L2 U2 B D B'",
      "R D' R' U R2 D' L' F2 L' D' L2 D' R2",
      "D B U L2 U2 L2 B2 D' B D' R2 D R2",
      "F U2 F2 D' F U2 F2 D2 B R2 B' D' F2",
      "F U2 F2 D' B' L2 B D2 F2 U2 F D' F2",
      "F U2 F2 D' B' L2 B' D2 F' D B2 D2 F2",
      "B2 U L2 D2 R' U2 R D2 L' B2 L' U' B2",
      "B2 D F2 D2 B' U2 B D2 F' L2 F' D' B2",
      "F2 R F' U2 F' U2 F R' U F' U' F U F'",
      "B' U R' L U2 L' U' L U2 R U L' U2 B",
      "L F' L B L2 F L' B' U2 L U' L' U L",
      "F B U F' U L2 U L2 U' B L2 B' U B'",
      "B2 R2 B U' R' U2 R U' R' U' R B' R2 B2",
      "L2 F L2 B' U2 B U2 F U2 F2 U' F U' F'",
      "F2 R B' R2 F' R2 B R' U F' U' F U F'",
      "F' D' L' D F2 U' F' L U' L2 U2 L2 U L'",
      "L F2 R U R' F U' B' U F' U' F2 B L'",
      "B L2 B' U2 B U2 B' U F U' F' B2 L2 B2",
      "R L2 D' B D R' B L B' U2 B' U B L",
      "F' L2 F2 U2 F' U' F U B' U2 F' B2 L2 B'",
      "F B U F' D F2 U F2 D' B L2 B' U B'",
      "B2 D F' L2 F B' U' B D' B2 U B U2 B'",
    ],
  },
  {
    family: 'LFFR',
    values: [
      "L' U2 B L2 F2 B R2 D2 F' R2 F' B2 L'",
      "L' U2 F' B2 D2 F' R2 D2 F2 B U2 B L'",
      "L2 D R' F2 R' B2 L2 U R2 F2 R B2 R'",
      "F2 R2 U' L2 B2 R F2 R D' R L2 B2 R'",
      "R2 U L2 B2 R F2 R D R L2 B2 R' F2",
      "F2 D' L2 U F2 R U' L2 U R' F2 L2 D",
      "R2 B2 D L2 U' B' D F2 D' B L2 B2 D'",
      "D' R2 B2 D L2 U' B' D F2 D' B L2 B2",
      "L2 B2 D R2 U' F' D B2 D' F L2 F2 D'",
      "D' L2 B2 D R2 U' F' D B2 D' F L2 F2",
      "L' U R L U' L' U R' U' L U L' U' L",
      "L' U L' U L' U' R' U L U' R L U' L",
      "F' U' F U L U2 L' U' F' U L U2 L' F",
      "L U L' F' U B' U' F U B U' L U' L'",
      "L U' L' U B' U' F' U B U' F L U L'",
      "L' U L U F U' B' U F' U' B L' U' L",
      "L2 U' L U B' L B L U' L B' L B L'",
    ],
  },
  {
    family: 'LFFR',
    values: [
      "D B D' L2 D2 L2 B2 U B D' R2 D L2 D2 L2 R2",
      "D' B U B2 R2 D2 R2 D' B D L2 R2 D2 R2 D L2",
      "F U2 F2 D' F' D2 B' R2 B D2 F2 U2 F2 D F2",
      "F U2 F2 D' F' D2 B' R2 B' D B2 D2 F2",
      "F' D2 B2 D B' L2 B' D2 F' D' F2",
      "B U B2 D' B U B' D B2 U2 B'",
      "B2 D B' U B D' B2 U B U2 B'",
      "L U' L' U2 L' D' R B2 R' D L",
    ],
  },
  {
    family: 'LFFR',
    values: [
      "R2 F2 U R2 U' R2 L D R2 D' R2 L' F2 R2",
      "B2 R2 F' D F R2 L2 D B' U' B D' L2 B2",
      "L2 B2 F2 U L' F2 L U' R' D2 R B2 F2 L2",
      "L' U' L2 F2 R' D R2 L D L' D' R' L' F2",
      "F' L2 D' R U' B' U B U R' D U' L2 F",
      "F' R L2 D' U' B' U B D U R' U' L2 F",
      "F' L2 D' U' R' B' R U R' B R D L2 F",
      "L U F U B U2 F' U' B' U R' L' U2 R",
    ],
  },
  {
    family: 'LFFR',
    values: [
      "F R' U2 R' D' L F2 L' D' L2 B L2 D2 R2",
      "B2 L2 B' U B L2 R2 U F' D' F U' R2 B2",
      "R2 U F B' R2 B D F' U' F D' F' U2 R2",
      "R2 U2 B' D B U' B' D' F R2 F' B U R2",
      "F B2 D B2 U' B U B2 D2 R2 D F' B",
      "F B2 D B2 U' B D' B2 U2 R2 U' F' B",
      "F L' D2 L U2 L' D2 L F' U' F U' F'",
      "B' U' R B L B' R' B L' U' B' U2 B",
      "B' D' R2 F R2 F' U D' F' U' F D2 B",
      "L' U L F' L2 U' F L' F' U L' F L'",
    ],
  },
  {
    family: 'LFFR',
    values: [
      "R' B2 D L' U L' U' L D' B2 R' U R2",
      "D F2 D' L2 U B2 L D' R2 D L' B2 L2",
      "L2 D L R U2 L B2 R U R' B2 R' F2",
      "F2 D' L2 U B2 L D' R2 D L' B2 L2 D",
      "F2 D' L2 U B2 L D' R2 D L' B2 L2 U2 D",
      "L U2 F' U' F L' F' U2 L U L' U' F",
    ],
  },
  {
    family: 'LFFR',
    values: [
      "L2 D2 B2 L2 F2 U L' D2 L U R' B2 R' F2",
      "L2 D2 F2 R2 F2 D R' U2 R D L' B2 L' B2",
      "B2 D F' D2 B' U B D B' D U' F D' B'",
      "B U2 R' U2 B' U2 F2 U B U' F2 R U B'",
      "B U' F' L2 D F U2 F U2 F2 D' L2 F B'",
      "F2 R2 F2 U F2 R2 D B' R2 B D' B' R2 B F2",
      "F2 R2 L2 U R U' B2 D' B2 R2 D R D' L2 F2",
      "B U' F' L2 D F' D' F2 U2 B' U2 B2 L2 B2",
      "D2 B U' F' L2 D F' D' F2 U2 B' D2 F2 R2 F2",
      "D2 B U' F' L2 D F' D' B2 D2 B' U2 B2 R2 F2",
      "B U' F' L2 D F' D' B2 D2 B' D2 F2 L2 B2",
      "F R' F' L2 F' D F2 D' R D F2 D' F L2",
    ],
  },
  {
    family: 'LFFR',
    values: [
      "R U R F2 L' B2 L' D' L B2 L F2 R2",
      "R' U R' U' R D' F2 U2 F2 R U R' D",
      "D R' U R' U' R D' F2 U2 F2 R U R'",
      "R U' R' F U' B' U F' U' B R U2 R'",
      "R B' R' U' R B L R' F U2 F' U' L'",
      "R' U R' U' R D' F2 U2 F2 R U R' U' D",
      "R' U' R U' R' U2 R2 U' L' U R' U' L",
    ],
  },
  {
    family: 'LFFR',
    values: [
      "F2 U' F2 U F2 R2 F2 L' U R2 U' L F2 R2",
      "D' F2 U' F2 D R2 B2 R2 F' U B2 U' F R2 B2",
      "D' L' F2 U2 L' U2 F2 D L2 U2 L U' F2 U' L2",
      "F2 U' F2 D R2 B2 R2 F' U B2 U' F R2 B2 D'",
      "F' U' B L2 B' U B2 R2 F' D F R2 F B2",
      "F' L' B' R U' R' B R U2 R' U' L F' U' F2",
      "B R B' D2 R' D2 L D2 F2 R F' L' F' D2",
      "B' U2 L' U' L B U' L' U2 L B' U2 B",
      "B' R' B U2 B' R B2 D2 F' L F D2 B'",
      "L U2 R D2 L' D' L2 D' R' U B2 U L'",
      "R B2 R F2 L' F' L2 F' R' B D2 B R'",
    ],
  },
];

const LRFF: Alg[] = [
  {
    family: 'LRFF',
    values: [
      "R B2 R2 U2 B2 R' B2 U2 R U' R2 U B2 U' R2",
      "R' D2 F2 L' F2 D2 R2 B2 R' U' R2 U B2 U' R2",
      "R' D2 F2 R' D2 B2 R2 U2 L' U' R2 U B2 U' R2",
      "F' U' F U2 R2 B2 U B' D B D' B U' B2 R2",
      "F' R2 D' L2 D2 B' D' R2 D' L2 D F' U F2",
      "F2 L2 F' R' F L2 D2 B' L B D2 F2 R",
      "B U' F U2 L U' L' F' B' U2 L' U L",
      "D R2 U' R2 B R U2 R2 U' R B' U R2 D' U2 R'",
      "F L2 U L2 F L2 B' U' F2 U' F B U' F L2 F'",
      "R' U' R D' F2 D U2 R D' R' F2 R2 U R' D R'",
      "R2 U' B2 U B D' R2 U F B' U' B D F U F'",
      "F' B' U2 F2 B R' B D2 F B' R F2 U2 B L B'",
      "F' U R U R D R' U' R D B' L2 D' B D' R2",
      "D' B U2 B' D L U' L' D' B U' B' D L U2 L'",
      "B U2 B' D L U' L' D' B U' B' D L U2 L' D'",
      "R' U R2 U2 R2 U' R L2 D2 R' D2 L2 U2 R U R'",
      "B2 R B U2 R' U B2 U2 R U' B2 U B' R' U2 B'",
      "F2 U2 F' D U R U R2 D' F D R' U R2 D' F",
      "L U R L' U R2 D' F2 L2 D L U L' U' F2 R",
      "B' R' U R U B2 D2 L' U L D' L2 U' L D' B'",
      "R' U2 B' R F2 U2 F' R F' R F' B' R2 F B2 R",
      "R2 B' R B2 U2 B' R U2 F D U R2 D' U' R F'",
      "F2 D' L2 U L' U2 L U' L2 D F2 D' L U' L' D",
      "R B L' B' R' B2 R' D2 R B' L2 F L F2 L2 B'",
      "F R2 B2 R' B' R F L' F' R F D2 L F' R F'",
      "L U2 L2 B2 L2 B' U' B' R' L F U F' L2 U2 R",
      "B' U2 F U' B D2 U' F' U' B' U2 F U B D2 F'",
    ],
  },
  {
    family: 'LRFF',
    values: [
      "B U' F2 U L F2 L' B' R U2 R' U' F2",
      "D L D' F2 L2 U' L2 D F2 L' D' F2 U F2",
      "D' F' U2 F' U2 F D R2 D' F U F' D R2",
      "D' B' R2 F' R2 B D R2 D' F U F' D R2",
      "F D B' D B2 D F D' B L2 D' B2 D' F2",
      "F2 U' L2 B2 R D L B2 R2 U' L U' R F2",
      "F' U2 F' U2 F D R2 D' F U F' D R2 D'",
      "B' R2 F' R2 B D R2 D' F U F' D R2 D'",
      "L D' F2 L2 U' L2 D F2 L' U' R2 U R2",
      "L D' F2 L2 U' L2 D F2 L' D' F2 U F2 D",
      "L2 D' B2 D L' U2 L D' B2 D L' U2 L'",
    ],
  },
  {
    family: 'LRFF',
    values: [
      "L D F2 D' L2 U L' D R' D R' D' R2 D' L2",
      "L2 B D' L2 F L2 B D' B2 L2 U' F' U' F2",
      "R' U' R U2 B2 L U' L' U L U L' B2",
      "F' L F2 L' U' F2 U F2 U R U2 R' F",
      "F' L F2 L' D' L2 U L2 D R U2 R' F",
      "L' U' B' U' B U' L F' L F L2 U' L",
      "L' U' B' U' B2 L2 D L D' L B' U2 L",
      "R' U' F' U L' U L U' L F' L' F2 R",
      "L' D2 F2 L' U2 R2 L D U B2 R' U R' D L'",
      "R' D2 F2 D R2 U L' U' L U' R2 D' F2 D2 R",
      "R' F2 L D' L D' B' R2 B D2 L2 F' U2 F' R",
      "R2 D2 U R' D2 R D2 B2 R B2 U' L' D2 R2 L",
      "L' U2 L2 F2 D R' F2 U' R U R F2 D' L' F2",
      "R' F2 L D' L D' F' U2 B R2 D2 B' U2 F' R",
      "R' U L2 D F2 D2 L' U' L D2 F2 D' L2 U' R",
      "B2 D F2 D' R2 F' L2 F R2 B' D U2 F2 D' B'",
      "B2 D F2 D R2 F D2 B' L2 D2 F' D' F2 D' B'",
      "R' U' R U2 B U2 R' U' R U R B' R' B U' B'",
      "R' U' R U' R U2 R2 U2 R' B' R2 B U F' U F",
      "R' D' F U' F U F' U F U2 F' U2 F' D U R",
      "R' U R U' R U2 R B R B' R B R2 B' U2 R'",
      "R U2 R' U' R U' R' L U2 L2 U' L2 U' L2 U2 L",
      "F U F' U F U2 F' R U2 R2 U' R2 U' R2 U2 R",
      "L U2 L2 U' L2 U' L2 U2 L B U B' U B U2 B'",
      "B U2 B R' B2 R B R' B R U2 B' U' B' U B",
      "F R U' R' U2 F' U' L U2 L2 U' L2 U' L2 U L",
      "R' U' F' U F U' F R' F D' F' D F' R U R",
      "L' U L F U' F' U2 L' U' L F' L F L2 U' L",
      "R' U' R U' R U2 R2 D' F2 U' F2 D R",
    ],
  },
  {
    family: 'LRFF',
    values: [
      "R D' R2 U2 F2 L' U' L F2 R U2 R2 D R2",
      "R B2 R2 D' F2 D R2 U' B2 R D L2 D' R2",
      "B U L2 U2 L2 B2 D' B' R2 U R2 U' B2 D",
      "B2 R U' R2 D L2 B2 D' B2 R D L2 D' B2",
      "D B U L2 U2 L2 B2 D' B' R2 U R2 U' B2",
      "D B' D B D2 F2 R2 U2 F' U' F U2 R2 U' F2",
      "F U2 F' U' R2 U' B U F U' F' B' U R2",
      "F U' B U2 F U F2 D' L2 D L2 B L2 B2",
      "F L' B2 R2 B' D B D' R2 B2 L F'",
      "L' B2 R2 B' D B D' R2 B2 L F' U2 F",
    ],
  },
  {
    family: 'LRFF',
    values: [
      "L' U B2 U' B2 U' L' U L2 D' B2 D B2",
      "L' D L2 U' L2 D' L' U L2 D' B2 D B2",
      "R U' B2 U B2 U R U' R2 D B2 D' B2",
      "R D' R2 U R2 D R U' R2 D B2 D' B2",
      "R2 U' F2 U R' B2 R U' F2 U R' B2 R'",
      "R2 F' R U2 F' U2 F R2 B' R F R2 B",
      "R2 B' D R2 F' R2 F D2 B' D B R2 B",
      "R2 B' D2 F D' F' R2 F' R2 F D' R2 B",
      "R2 B' D2 F D' B' D2 F' D2 B D' R2 B",
      "R' U2 R' B D2 B' R U2 R' B D2 B' R2",
      "R' D R2 U' B2 U B2 R' U R2 D' R2",
      "R' D R2 U' B2 U B2 R' D B2 D' B2 D'",
    ],
  },
  {
    family: 'LRFF',
    values: [
      "D' B D' B' D2 F2 L2 U2 F U F' U2 L2 U F2",
      "D' B' U' R2 U2 R2 B2 D B L2 U' L2 U B2",
      "F U B' U2 F' U' F2 D R2 D' R2 B' R2 F2 B2",
      "F U2 F' D F2 U L F' U F U' L' U' F2 D'",
      "F U2 F' D F2 U2 B U' F' U F B' U2 F2 D'",
      "F U2 F' D' F2 U2 B' U' F' U F B U2 F2 D",
      "F R B2 L2 B D' B' D L2 B2 R' F U2 F2",
      "F' U B' U2 F' U' F2 D R2 D' R2 B' R2 B2",
      "F' R B2 L2 B D' B' D L2 B2 R' F",
      "R B2 L2 B D' B' D L2 B2 R' F U2 F'",
    ],
  },
  {
    family: 'LRFF',
    values: [
      "R' D F2 R2 U R2 D' F2 R D F2 U' F2 D'",
      "R' D F2 R2 U R2 D' F2 R U L2 U' L2",
      "B' U F2 U' R' F2 R B L' U2 L U F2",
      "D F U2 F U2 F' D' L2 D F' U' F D' L2",
      "D B L2 F L2 B' D' L2 D F' U' F D' L2",
      "D' R' D F2 R2 U R2 D' F2 R D F2 U' F2",
      "F U2 F U2 F' D' L2 D F' U' F D' L2 D",
      "F2 U R2 B2 L' D' R' B2 L2 U R' U L' F2",
      "F' D' B D' B2 D' F' D B' R2 D B2 D F2",
      "B L2 F L2 B' D' L2 D F' U' F D' L2 D",
      "R2 D B2 D' R U2 R' D B2 D' R U2 R",
    ],
  },
  {
    family: 'LRFF',
    values: [
      "B U B' D L2 D2 R2 F D' F U' F2 L2 D2 R2",
      "B2 R' U2 L2 U L2 U L2 U R U L2 U' B2",
      "B' D B' U B2 L2 D2 R2 F' U' F D' L2 D2 R2",
      "L U' B2 D2 R U D F2 U2 D R' U R2 B2",
      "F2 U F2 D' F' U2 F' D F U2 F' R2 U' R2 F2",
      "B2 L2 U L2 B U' B D' L2 F' D F L2 U D",
      "B' U2 B2 L' B' L B' U R' U R B",
      "B' U' R B' D B' D' B2 R2 U R B",
    ],
  },
  {
    family: 'LRFF',
    values: [
      "B2 L U2 R2 U' R2 U' R2 U' L' U' R2 U B2",
      "L2 B' L' F R2 F' L B' U F2 D F2 U' B2 L2",
      "L2 B' L' F R2 F' L B' D R2 D R2 D' B2 L2",
      "R' U B2 D2 L' U' D' F2 U2 D' L U' L2 B2",
      "B U L' B D' B D B2 L2 U' L' B'",
      "B U2 B2 R B R' B U' L U' L' B'",
    ],
  },
  {
    family: 'LRFF',
    values: [
      "B' D B' U L2 D2 R2 F U' F D' L2 D2 R2",
      "L' B R' B D2 L2 U2 R F' L F' R2 D2 L2",
      "R B' L B' D2 R2 U2 L' F R' F L2 D2 R2",
      "B D' B U' R2 D2 L2 F' U F' D R2 D2 L2",
      "L F' L' F U2 L' B' R B L' B2 R' B2 L2",
      "L2 F2 L B L' F2 L2 F' L' B' L F",
      "R2 F2 R' B' R F2 R2 F R B R' F'",
    ],
  },
  {
    family: 'LRFF',
    values: [
      "F B' U B L2 D F D' L2 U F' L2 U L2 U' L2",
      "F2 U F' D F2 U' R2 U' D2 L2 B' D L2 D R2 D'",
      "L' D L' U L2 D2 B2 U' R' U2 R' U R2 D B2",
      "R' U2 R2 U' L U' R2 U' R' U L' U' B2 R2 B2",
      "R' D' F2 D R2 U' R D' L D' L D L2 D R2",
      "L U L' U2 B2 R' U R U' R' U' R B2",
      "F R' F2 R U F2 U' F2 U' L' U2 L F'",
      "F R' F2 R D R2 U' R2 D' L' U2 L F'",
      "L U F U' R U' R' U R' F R F2 L'",
      "R D2 F2 R U2 R' L2 D' U' B2 L U' L D' R",
      "L F2 R' D R' D B L2 B' D2 R2 F U2 F L'",
      "L2 D2 U' L D2 L' D2 B2 L' B2 U R D2 R' L2",
      "R U2 R2 F2 D' L F2 U L' U' L' F2 D R F2",
      "L F2 R' D R' D F U2 B' L2 D2 B U2 F L'",
      "L U' R2 D' F2 D2 R U R' D2 F2 D R2 U L'",
      "B2 D' F2 D L2 F R2 F' L2 B D' U2 F2 D B",
      "B2 D' F2 D' L2 F' D2 B R2 D2 F D F2 D B",
      "L U L' U2 B' U2 L U L' U' L' B L B' U B",
      "L U L' U L' U2 L2 U2 L B L2 B' U' F U' F'",
      "L D F' U F' U' F U' F' U2 F U2 F D' U' L'",
      "L U' L' U L' U2 L' B' L' B L' B' L2 B U2 L",
      "L' U2 L U L' U R' L U2 R2 U R2 U R2 U2 R'",
      "F' U' F U' F' U2 F L' U2 L2 U L2 U L2 U2 L'",
      "R' U2 R2 U R2 U R2 U2 R' B' U' B U' B' U2 B",
      "F' L' U L U2 F U R' U2 R2 U R2 U R2 U' R'",
      "B' U2 B' L B2 L' B' L B' L' U2 B U B U' B'",
      "L U F U' F' U F' L F' D F D' F L' U' L'",
      "R U' R' F' U F U2 R U R' F R' F' R2 U R'",
      "L F' L2 F L2 U' L' U L' U' L' U F' L2 F L'",
      "L U L' F' U2 F2 U F2 U F2 U2 F' U L U L'",
      "L U L' U2 B' U F U F' U' F' L F L' U2 B",
      "L U L' U2 B' U' B U' F' L2 F L' U' L2 U L",
      "L U L' U L' U2 L2 D F2 U F2 D' L'",
    ],
  },
  {
    family: 'LRFF',
    values: [
      "L D2 F2 L D2 B2 L2 U2 R U L2 U' B2 U L2",
      "L D2 F2 R F2 D2 L2 B2 L U L2 U' B2 U L2",
      "L' B2 L2 U2 B2 L B2 U2 L' U L2 U' B2 U L2",
      "F U F' U2 L2 B2 U' B D' B' D B' U B2 L2",
      "F L2 D R2 D2 B D L2 D R2 D' F U' F2",
      "F2 R2 F L F' R2 D2 B R' B' D2 F2 L'",
      "B' U F' U2 R' U R F B U2 R U' R'",
      "F B U2 F2 B' L F U2 B2 R F' B D2 F R' B",
      "R F' R U R2 F' U2 B' R B R2 F2 R U F2 R2",
      "B U2 F2 D' L' B2 L B L' B L B D F2 U2 B'",
      "L' U2 L' B' L2 B L' D2 F D2 L D2 F' D2 U2 L",
      "L' U2 B L' D2 B' L' F2 R' F' L' F' R B' R' B",
      "R2 F R F' R F2 B D2 F' R B R' F D2 F2 B'",
      "R' U2 B R2 B L F' U2 F' L' B2 R L F2 R L'",
      "L2 B2 R B D B R2 L' F2 L2 U L F' U' F' R",
      "F' B D2 F2 D L2 D' F2 D2 B' U2 F U2 F2 U' F'",
      "B' U2 F' D2 B D B2 D F U' L2 F U' B U F'",
      "R2 U' R2 D2 F' D' B2 D F D2 U B2 U B2 U' B2",
      "L' D L2 F2 U F2 L2 D' B2 L2 U' L' U R' U R",
      "D2 B L2 B' D F' U2 F2 U' F' U F2 D B' R2 B",
      "B L2 B' D F' U2 F2 U' F' U F2 D B' R2 B D2",
      "F' D F2 D2 B L2 B' D2 F2 D' U2 F U2 F2 U' F'",
      "L' U B2 D L' U' L2 D' R' L U2 R U' B2 L2 B2",
      "R' U2 R L' D L2 U L D' B2 U' L U B2 L2 B2",
      "B2 D L2 F B D' B U R2 U2 B D U' F' D' B'",
      "R' U2 R' L U R2 U L D' F2 D' R2 L D2 R L",
      "R' U F2 U2 F2 U2 F2 R U2 B2 L2 U L U' L2 B2",
      "R2 F2 B2 L F U2 F L' B' R2 B' U2 L' U2 R L",
    ],
  },
];

export const U_ZBLL: Alg[] = [...BBFF, ...BFFB, ...FFLR, ...FRLF, ...LFFR, ...LRFF];
